#!/usr/bin/env python3
"""Summarize a one-shot Track C anchor-gated blend query diagnostic.

This script is inactive unless the full support/canonical blend posthoc gate has
already passed.  It reads one held-out query JSON generated by
``evaluate_latentfm_trackc_anchor_gated_support_teacher_blend_20260623.py`` with
``--scope heldout_query_once``.

The result is diagnostic only.  It must not be used to tune alpha, route,
checkpoint, threshold, or any future branch selection.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import Any

import numpy as np


ROOT = Path("/data/cyx/1030/scLatent")
DEFAULT_POSTHOC_GATE_JSON = (
    ROOT / "reports/latentfm_trackc_anchor_gated_support_teacher_blend_posthoc_gate_20260623.json"
)
PASS_POSTHOC_STATUS = "trackc_anchor_gated_support_teacher_blend_posthoc_gate_pass"
SUPPORTED_STATUS = "trackc_anchor_gated_blend_query_diagnostic_candidate_supported"
NOT_SUPPORTED_STATUS = "trackc_anchor_gated_blend_query_diagnostic_not_supported"
FAIL_CLOSED_STATUS = "trackc_anchor_gated_blend_query_precondition_fail_closed"

QUERY_GROUPS = (
    "heldout_query_multi_final_only",
    "heldout_query_multi_seen_final_only",
    "heldout_query_multi_unseen1_final_only",
    "heldout_query_multi_unseen2_final_only",
)


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def finite(value: Any) -> float | None:
    if value is None:
        return None
    try:
        out = float(value)
    except Exception:
        return None
    return out if np.isfinite(out) else None


def fmt(value: Any) -> str:
    value = finite(value)
    return "NA" if value is None else f"{value:+.6f}"


def rows_for(payload: dict[str, Any], group: str) -> list[dict[str, Any]]:
    return ((payload.get("groups") or {}).get(group) or {}).get("condition_metrics") or []


def equal_ds_mean(rows: list[dict[str, Any]], key: str) -> float | None:
    by_ds: dict[str, list[float]] = defaultdict(list)
    for row in rows:
        value = finite(row.get(key))
        if value is not None:
            by_ds[str(row.get("dataset"))].append(value)
    vals = [mean(v) for v in by_ds.values() if v]
    return mean(vals) if vals else None


def bootstrap_equal_ds(
    rows: list[dict[str, Any]],
    key: str,
    *,
    n_boot: int,
    seed: int,
) -> dict[str, Any]:
    by_ds: dict[str, list[float]] = defaultdict(list)
    for row in rows:
        value = finite(row.get(key))
        if value is not None:
            by_ds[str(row.get("dataset"))].append(value)
    observed = equal_ds_mean(rows, key)
    if observed is None or not by_ds:
        return {"observed": None, "ci_low": None, "ci_high": None, "n_datasets": 0}
    rng = np.random.default_rng(seed)
    samples = []
    for _ in range(int(n_boot)):
        ds_vals = []
        for vals in by_ds.values():
            arr = np.asarray(vals, dtype=np.float64)
            picked = rng.choice(arr, size=arr.size, replace=True)
            ds_vals.append(float(np.mean(picked)))
        samples.append(float(np.mean(ds_vals)))
    arr = np.asarray(samples, dtype=np.float64)
    return {
        "observed": float(observed),
        "ci_low": float(np.quantile(arr, 0.025)),
        "ci_high": float(np.quantile(arr, 0.975)),
        "p_positive": float(np.mean(arr > 0.0)),
        "p_improve_pp": float(np.mean(arr > 0.02)),
        "p_harm_pp": float(np.mean(arr < -0.02)),
        "p_mmd_harm": float(np.mean(arr > 0.005)),
        "p_mmd_improve": float(np.mean(arr < -0.005)),
        "n_datasets": int(len(by_ds)),
    }


def row_brief(row: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "dataset",
        "condition",
        "anchor_pearson_pert",
        "blend_pearson_pert",
        "blend_delta_vs_anchor_pearson_pert",
        "anchor_test_mmd_clamped",
        "blend_test_mmd_clamped",
        "blend_delta_vs_anchor_test_mmd_clamped",
    )
    out: dict[str, Any] = {}
    for key in keys:
        value = row.get(key)
        if key in {"dataset", "condition"}:
            out[key] = str(value)
        else:
            out[key] = None if finite(value) is None else float(value)
    return out


def worst_rows(rows: list[dict[str, Any]], key: str, *, reverse: bool, n: int = 8) -> list[dict[str, Any]]:
    scored = []
    for row in rows:
        value = finite(row.get(key))
        if value is not None:
            scored.append((value, str(row.get("dataset")), str(row.get("condition")), row))
    scored.sort(key=lambda item: (item[0], item[1], item[2]), reverse=reverse)
    return [row_brief(row) for _, _, _, row in scored[: int(n)]]


def group_summary(rows: list[dict[str, Any]], *, n_boot: int, seed_base: int) -> dict[str, Any]:
    return {
        "n_rows": int(len(rows)),
        "blend_pearson_pert": bootstrap_equal_ds(rows, "blend_pearson_pert", n_boot=n_boot, seed=seed_base),
        "anchor_pearson_pert": bootstrap_equal_ds(rows, "anchor_pearson_pert", n_boot=n_boot, seed=seed_base + 1),
        "delta_pearson_pert": bootstrap_equal_ds(
            rows,
            "blend_delta_vs_anchor_pearson_pert",
            n_boot=n_boot,
            seed=seed_base + 2,
        ),
        "blend_mmd_clamped": bootstrap_equal_ds(rows, "blend_test_mmd_clamped", n_boot=n_boot, seed=seed_base + 3),
        "anchor_mmd_clamped": bootstrap_equal_ds(rows, "anchor_test_mmd_clamped", n_boot=n_boot, seed=seed_base + 4),
        "delta_mmd_clamped": bootstrap_equal_ds(
            rows,
            "blend_delta_vs_anchor_test_mmd_clamped",
            n_boot=n_boot,
            seed=seed_base + 5,
        ),
        "worst_pp_delta_rows": worst_rows(
            rows,
            "blend_delta_vs_anchor_pearson_pert",
            reverse=False,
        ),
        "worst_mmd_delta_rows": worst_rows(
            rows,
            "blend_delta_vs_anchor_test_mmd_clamped",
            reverse=True,
        ),
    }


def precondition_reasons(query_payload: dict[str, Any], posthoc_gate: dict[str, Any]) -> list[str]:
    reasons: list[str] = []
    if posthoc_gate.get("status") != PASS_POSTHOC_STATUS:
        reasons.append(f"posthoc_gate_not_pass:{posthoc_gate.get('status')}")
    if query_payload.get("scope") != "heldout_query_once":
        reasons.append(f"query_payload_wrong_scope:{query_payload.get('scope')}")
    safety = query_payload.get("safety") or {}
    if safety.get("heldout_query_read") is not True:
        reasons.append("query_payload_does_not_mark_heldout_query_read")
    if safety.get("query_result_may_select_or_tune") is not False:
        reasons.append("query_payload_allows_selection_or_tuning")
    if safety.get("canonical_multi_selection") is not False:
        reasons.append("query_payload_marks_canonical_multi_selection")
    for group in QUERY_GROUPS:
        if not rows_for(query_payload, group):
            reasons.append(f"missing_query_group:{group}")
    return reasons


def decide(payload: dict[str, Any]) -> dict[str, Any]:
    reasons = list(payload.get("precondition_reasons") or [])
    primary = ((payload.get("groups") or {}).get("heldout_query_multi_final_only") or {})
    primary_pp = primary.get("delta_pearson_pert") or {}
    primary_mmd = primary.get("delta_mmd_clamped") or {}
    unseen2 = ((payload.get("groups") or {}).get("heldout_query_multi_unseen2_final_only") or {})
    unseen2_mmd = unseen2.get("delta_mmd_clamped") or {}

    pp_obs = finite(primary_pp.get("observed"))
    pp_pos = finite(primary_pp.get("p_positive"))
    mmd_harm = finite(primary_mmd.get("p_mmd_harm"))
    unseen2_harm = finite(unseen2_mmd.get("p_mmd_harm"))

    if not reasons:
        if pp_obs is None or pp_obs <= 0.0:
            reasons.append("query_multi_pp_delta_not_positive")
        if pp_pos is None or pp_pos < 0.80:
            reasons.append("query_multi_pp_positive_probability_lt_0p80")
        if mmd_harm is None or mmd_harm > 0.80:
            reasons.append("query_multi_mmd_hard_harm_probability_gt_0p80")
        if unseen2_harm is None or unseen2_harm > 0.80:
            reasons.append("query_unseen2_mmd_hard_harm_probability_gt_0p80")

    if payload.get("precondition_reasons"):
        status = FAIL_CLOSED_STATUS
        action = "do_not_read_or_reuse_query_until_preconditions_are_fixed"
    elif reasons:
        status = NOT_SUPPORTED_STATUS
        action = "close_anchor_gated_blend_branch_do_not_tune_on_query"
    else:
        status = SUPPORTED_STATUS
        action = "record_final_query_diagnostic_do_not_tune_on_query"
    return {
        "status": status,
        "action": action,
        "reasons": reasons,
        "rules": [
            "full support/canonical blend posthoc gate must pass before query summary is valid",
            "query payload must be generated with --scope heldout_query_once",
            "query result is diagnostic only and cannot select/tune alpha, route, checkpoint, threshold, or future branches",
            "primary query_multi pearson_pert delta must be positive with bootstrap p_positive >= 0.80",
            "primary query_multi MMD hard-harm probability p(delta_clamped > +0.005) must be <= 0.80",
            "query_multi_unseen2 MMD hard-harm probability must be <= 0.80",
        ],
    }


def summarize(args: argparse.Namespace) -> dict[str, Any]:
    query_payload = load_json(args.query_json)
    posthoc_gate = load_json(args.posthoc_gate_json)
    groups = {}
    for idx, group in enumerate(QUERY_GROUPS):
        groups[group] = group_summary(rows_for(query_payload, group), n_boot=int(args.n_boot), seed_base=1000 + idx * 10)
    payload = {
        "query_json": str(args.query_json),
        "posthoc_gate_json": str(args.posthoc_gate_json),
        "query_scope": query_payload.get("scope"),
        "safety": query_payload.get("safety") or {},
        "precondition_reasons": precondition_reasons(query_payload, posthoc_gate),
        "groups": groups,
    }
    payload["decision"] = decide(payload)
    payload["status"] = payload["decision"]["status"]
    payload["action"] = payload["decision"]["action"]
    return payload


def render(payload: dict[str, Any]) -> str:
    decision = payload["decision"]
    primary = payload["groups"]["heldout_query_multi_final_only"]
    unseen2 = payload["groups"]["heldout_query_multi_unseen2_final_only"]
    lines = [
        "# Track C Anchor-Gated Blend One-Shot Query Diagnostic",
        "",
        f"Status: `{decision['status']}`",
        f"Action: `{decision['action']}`",
        "",
        "## Boundary",
        "",
        "This is a final diagnostic report only. Query results must not be used for route, checkpoint, alpha, threshold, or branch selection.",
        "",
        "## Primary Metrics",
        "",
        f"* query_multi rows: `{primary['n_rows']}`",
        f"* query_multi pp delta: `{fmt(primary['delta_pearson_pert'].get('observed'))}`",
        f"* query_multi pp p_positive: `{fmt(primary['delta_pearson_pert'].get('p_positive'))}`",
        f"* query_multi MMD-clamped delta: `{fmt(primary['delta_mmd_clamped'].get('observed'))}`",
        f"* query_multi MMD hard-harm probability: `{fmt(primary['delta_mmd_clamped'].get('p_mmd_harm'))}`",
        f"* query_unseen2 rows: `{unseen2['n_rows']}`",
        f"* query_unseen2 MMD hard-harm probability: `{fmt(unseen2['delta_mmd_clamped'].get('p_mmd_harm'))}`",
        "",
        "## Reasons",
        "",
    ]
    if decision["reasons"]:
        lines.extend(f"* `{reason}`" for reason in decision["reasons"])
    else:
        lines.append("* none")
    lines.extend(["", "## Inputs", ""])
    lines.append(f"* query_json: `{payload['query_json']}`")
    lines.append(f"* posthoc_gate_json: `{payload['posthoc_gate_json']}`")
    lines.extend(["", "## Worst Query Rows", ""])
    for title, rows in (
        ("Lowest query_multi pp deltas", primary.get("worst_pp_delta_rows") or []),
        ("Highest query_multi MMD deltas", primary.get("worst_mmd_delta_rows") or []),
    ):
        lines.append(f"### {title}")
        lines.append("")
        if not rows:
            lines.append("* none")
        else:
            for row in rows[:8]:
                lines.append(
                    "* "
                    f"`{row.get('dataset')}` / `{row.get('condition')}`: "
                    f"pp_delta `{fmt(row.get('blend_delta_vs_anchor_pearson_pert'))}`, "
                    f"mmd_delta `{fmt(row.get('blend_delta_vs_anchor_test_mmd_clamped'))}`"
                )
        lines.append("")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--query-json", type=Path, required=True)
    ap.add_argument("--posthoc-gate-json", type=Path, default=DEFAULT_POSTHOC_GATE_JSON)
    ap.add_argument("--out-json", type=Path, required=True)
    ap.add_argument("--out-md", type=Path, required=True)
    ap.add_argument("--n-boot", type=int, default=2000)
    args = ap.parse_args()

    payload = summarize(args)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    args.out_md.write_text(render(payload), encoding="utf-8")
    print(json.dumps({"status": payload["status"], "out_md": str(args.out_md)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
